name: Build F-Droid Repo

on:
  push:
    branches: [ main ]
    paths:
      - 'repo/**'
      - 'metadata/**'
      - '.github/workflows/fdroid.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install fdroidserver
        run: pip install fdroidserver

      - name: Build F-Droid repo index
        run: |
          fdroid update --create-metadata --verbose --repo repo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo