name: F-Droid Repo Index

on:
  push:
    paths:
      - 'repo/**'
  workflow_dispatch:

jobs:
  fdroid-index:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v4

      - name: Instala fdroidserver
        run: pip install fdroidserver

      - name: Restaura keystore.p12 desde secret
        run: echo "${{ secrets.KEYSTORE_P12_B64 }}" | base64 --decode > keystore.p12

      - name: Restaura config.yml desde secret
        run: |
          echo "${{ secrets.FDROID_CONFIG_YML }}" > config.yml

      - name: Ejecuta fdroid update (índice F-Droid)
        run: fdroid update --create-metadata --verbose

      - name: Prepara archivos para publicación
        run: |
          mkdir publish
          cp -r repo publish/repo

      - name: Publica en gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          force_orphan: true
